Fix flaky FlowRunnerTest > exec1FailedKillAll
Sometimes the job6 status was SUCCEEDED if the flow killing took longer than usual, because it only slept for max 1 second.

Failure from Travis logs:

azkaban.execapp.FlowRunnerTest > exec1FailedKillAll FAILED
    java.lang.AssertionError: Wrong status for [job6] expected:<KILLED> but was:<SUCCEEDED>