Reproduce flaky FlowRunnerTest2 > testNormalFailure2
The test failure is:

azkaban.execapp.FlowRunnerTest2 > testNormalFailure2 FAILED
    java.lang.AssertionError: Wrong status for [jobb:innerJobB] expected:<CANCELLED> but was:<RUNNING>

azkaban.execapp.FlowRunnerTest2 > testNormalFailure2 STANDARD_ERROR
    testJob: joba1 FAILED
    testJob: jobd:innerJobA SUCCEEDED
    testJob: jobd:innerFlow2 RUNNING
    testJob: joba SUCCEEDED
    testJob: jobc RUNNING
    testJob: jobb:innerJobB RUNNING
    testJob: jobb:innerJobC RUNNING
    testJob: jobb:innerJobA SUCCEEDED
    ExecutableFlow: jobf FAILED_FINISHING
    ExecutableNode: joba1 FAILED
    ExecutableFlow: jobb RUNNING
    ExecutableNode: jobb:innerFlow READY
    ExecutableNode: jobb:innerJobB RUNNING
    ExecutableNode: jobb:innerJobA SUCCEEDED
    ExecutableNode: jobb:innerJobC RUNNING
    ExecutableNode: joba SUCCEEDED
    ExecutableFlow: jobd RUNNING
    ExecutableNode: jobd:innerJobA SUCCEEDED
    ExecutableNode: jobd:innerFlow2 RUNNING
    ExecutableNode: jobc RUNNING
    ExecutableNode: jobf READY
    ExecutableNode: jobe READY

 Analysis: when a job finishes, an event is fired about its status. The events are handled asynchronously in FlowRunner's progressGraph() loop. This test case is flaky because before ("jobb:innerJobA").succeedJob() and ("jobd:innerJobA").succeedJob() it waits for the node status of "joba1" to be FAILED, but it doesn't wait for that event to have been processed.