Fix flaky JobRunnerTest > testDelayedExecutionCancelledJob (#1442)
- Now instead of fixed 1s sleep we wait for max 10s for the node update count to be 2.
- This lets us use the luxury of additional sleep time (1s->2s) before killing the flow, so that there's a better chance for job getting inside its delayExecution() block.

Test failure was:

azkaban.execapp.JobRunnerTest > testDelayedExecutionCancelledJob FAILED
    java.lang.AssertionError: expected:<2> but was:<1>

It was faithfully reproduced when I removed the 1s sleep before assert on getNodeUpdateCount().