Fix flaky FileWatcherTest
The failure on Travis was:

  azkaban.user.FileWatcherTest > registerAndTake FAILED
      java.lang.AssertionError: expected:<1> but was:<2>
          at org.junit.Assert.fail(Assert.java:88)
          at org.junit.Assert.failNotEquals(Assert.java:834)
          at org.junit.Assert.assertEquals(Assert.java:645)
          at org.junit.Assert.assertEquals(Assert.java:631)
          at azkaban.user.FileWatcherTest.registerAndTake(FileWatcherTest.java:75)

This is familiar from previous life where we had a multi-threaded test. That test was working because it retried on read error and thus also tolerated 1 or 2 events from watch service.