Fix flaky test force_shutdown_after_timeout (#1844)
Fix #1842

Issue:

azkaban.utils.ExecutorServiceUtilsTest > force_shutdown_after_timeout STANDARD_ERROR
log4j:WARN No appenders could be found for logger (azkaban.utils.ExecutorServiceUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
azkaban.utils.ExecutorServiceUtilsTest > force_shutdown_after_timeout FAILED
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at azkaban.utils.ExecutorServiceUtilsTest.force_shutdown_after_timeout(ExecutorServiceUtilsTest.java:60)
azkaban.utils.ExecutorServiceUtilsTest

It failed at
assertThat(this.isTestThreadInterrupted).isTrue();

It's possible that the task has not been scheduled yet or has not had time to process the interrupt request.

Fix:

Replaced the test with a mock based test strategy.

The test requires a newer version of JDK. JDK 1.8.05 failed.
1.8.133 worked.

See
https://stackoverflow.com/questions/37527038/mockito-object-is-not-an-instance-of-declaring-class/37528479#37528479
for more information.